// <auto-generated />
namespace Blog.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Galery : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Galery));
        
        string IMigrationMetadata.Id
        {
            get { return "201903190957431_Galery"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
